[package]
name = "elisabot"
version = "0.1.0"
authors = ["Gabriele Belluardo <gabriele.belluardo@outlook.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
